export const LOADDATA_STARTED = 'LOADDATA_STARTED';
export const LOADDATA_SUCCEEDED = 'LOADDATA_SUCCEEDED';
export const LOADDATA_FAILED = 'LOADDATA_FAILED';
export const NAME_UPDATED = 'NAME_UPDATED';
export const COUNT_UPDATED = 'COUNT_UPDATED';
